version: "2"
services:
  rabbit:
    container_name: simplebank-rabbitmq
    image: rabbitmq:3.6-management
    ports:
        - "15673:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  postgres:
    container_name: simplebank-postgres
    image: postgres
    ports:
        - "5433:5432" # Exposing Postgres on different port for convenience
    environment:
        POSTGRES_DB: "orders"
        POSTGRES_PASSWORD: "password"
        POSTGRES_USER: "postgres"
    restart: always

  redis:
    container_name: simplebank-redis
    image: redis
    ports:
        - "6380:6379" # Exposing Redis on different port for convenience
    restart: always

  orders:
    container_name: simplebank-orders
    image: microservicesinaction/simplebank-orders:dev
    depends_on:
      - rabbit
      - postgres
    ports:
        - "8001:8000"
    links:
        - "rabbit:simplebank-rabbitmq"
        - "postgres:simplebank-postgres"
    environment:
        DB_PASSWORD: "password"
        DB_USER: "postgres"
        DB_HOST: "postgres"
        DB_NAME: "orders"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"

  products:
    container_name: simplebank-products
    image: microservicesinaction/simplebank-products:dev
    depends_on:
      - rabbit
      - redis
    ports:
        - "8002:8000"
    links:
        - "rabbit:simplebank-rabbitmq"
        - "redis:simplebank-redis"
    environment:
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        REDIS_INDEX: "11"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"

  gateway:
    container_name: simplebank-gateway
    image: microservicesinaction/simplebank-gateway:dev
    depends_on:
      - rabbit
    ports:
        - "8003:8000"
    links:
        - "rabbit:simplebank-rabbitmq"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"
